using AppointMe.Domain.DTO;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AppointMe.Domain.DTO;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Net.Http;

namespace AppointMe.Service.Pdf
{
    public class InvoicePdfGenerator
    {
        public static async Task<byte[]> GenerateAsync(InvoiceDTO invoice)
        {
            byte[]? logoBytes = null;

            if (!string.IsNullOrWhiteSpace(invoice.BusinessLogoUrl))
            {
                try
                {
                    // Many image hosts block requests without a User-Agent
                    using var http = new HttpClient();
                    http.DefaultRequestHeaders.UserAgent.ParseAdd("AppointMe/1.0");

                    var bytes = await http.GetByteArrayAsync(invoice.BusinessLogoUrl);

                    // Basic sanity check (avoid passing HTML/error pages as "image")
                    if (bytes != null && bytes.Length > 200)
                        logoBytes = bytes;
                }
                catch
                {
                    logoBytes = null; // ignore completely
                }
            }


            QuestPDF.Settings.License = LicenseType.Community;

            var doc = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);
                    page.Size(PageSizes.A4);
                    page.DefaultTextStyle(x => x.FontSize(11));

                    page.Header().Element(h => BuildHeader(h, invoice, logoBytes));
                    page.Content().Element(c => BuildContent(c, invoice));
                    page.Footer().AlignCenter().Text($"Generated by AppointMe • {DateTime.Now:dd MMM yyyy HH:mm}");
                });
            });

            return doc.GeneratePdf();
        }

        private static void BuildHeader(IContainer container, InvoiceDTO i, byte[]? logoBytes)
        {
            container.Column(col =>
            {
                col.Item().Row(row =>
                {
                    // LEFT: Business details
                    row.RelativeItem().Column(c =>
                    {
                        c.Item().Text(string.IsNullOrWhiteSpace(i.BusinessName) ? "Business" : i.BusinessName)
                            .FontSize(18).SemiBold();

                        if (!string.IsNullOrWhiteSpace(i.BusinessAddress))
                            c.Item().Text(i.BusinessAddress).FontColor(Colors.Grey.Darken2);

                        c.Item().PaddingTop(8).Text("INVOICE").FontSize(14).SemiBold();
                    });

                    // CENTER: Logo (optional)
                    if (logoBytes != null && logoBytes.Length > 0)
                    {
                        row.ConstantItem(120).AlignMiddle().AlignRight()
                            .Height(60)
                            .Image(logoBytes, ImageScaling.FitArea);
                    }

                    // RIGHT: Invoice meta
                    row.ConstantItem(220).AlignRight().Column(c =>
                    {
                        c.Item().Text($"Invoice #: {i.InvoiceNumber}").SemiBold();
                        c.Item().Text($"Issued: {i.IssuedAt:dd MMM yyyy}");
                        c.Item().Text($"Status: {i.Status}");
                        c.Item().Text($"Appointment: {i.AppointmentDate:dd MMM yyyy HH:mm}");
                    });
                });

                col.Item().PaddingVertical(10)
                    .LineHorizontal(1)
                    .LineColor(Colors.Grey.Lighten2);
            });
        }
        private static void BuildContent(IContainer container, InvoiceDTO i)
        {
            container.Column(col =>
            {
              
                col.Item().PaddingTop(10).Row(r =>
                {
                    r.RelativeItem().Column(c =>
                    {
                        c.Item().Text("Bill To").SemiBold().FontSize(12);
                        c.Item().Text(i.CustomerName ?? "Customer");
                        if (!string.IsNullOrWhiteSpace(i.CustomerEmail))
                            c.Item().Text(i.CustomerEmail).FontColor(Colors.Grey.Darken2);
                    });

                    r.ConstantItem(250).AlignRight().Column(c =>
                    {
                        if (!string.IsNullOrWhiteSpace(i.OrderNumber))
                            c.Item().Text($"Order #: {i.OrderNumber}");
                    });
                });

                col.Item().PaddingTop(15);

              
                col.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(5); // item
                        columns.RelativeColumn(1); // qty
                        columns.RelativeColumn(2); // unit
                        columns.RelativeColumn(2); // total
                    });

                    // Header
                    table.Header(header =>
                    {
                        header.Cell().Element(CellHeader).Text("Item");
                        header.Cell().Element(CellHeader).AlignRight().Text("Qty");
                        header.Cell().Element(CellHeader).AlignRight().Text("Unit");
                        header.Cell().Element(CellHeader).AlignRight().Text("Total");
                    });

                    // Rows
                    if (i.Lines != null && i.Lines.Any())
                    {
                        foreach (var l in i.Lines)
                        {
                            table.Cell().Element(CellBody).Column(c =>
                            {
                                c.Item().Text(l.Name ?? "Service").SemiBold();
                                if (!string.IsNullOrWhiteSpace(l.Category))
                                    c.Item().Text(l.Category).FontColor(Colors.Grey.Darken2).FontSize(10);
                            });

                            table.Cell().Element(CellBody).AlignRight().Text(l.Qty.ToString());
                            table.Cell().Element(CellBody).AlignRight().Text($"{l.UnitPrice:0.00} ден");
                            table.Cell().Element(CellBody).AlignRight().Text($"{l.LineTotal:0.00} ден").SemiBold();
                        }
                    }
                    else
                    {
                        table.Cell().ColumnSpan(4).Element(CellBody).AlignCenter()
                             .Text("No invoice lines.").FontColor(Colors.Grey.Darken2);
                    }

                    static IContainer CellHeader(IContainer c) =>
                        c.PaddingVertical(6).PaddingHorizontal(5)
                         .Background(Colors.Grey.Lighten3)
                         .BorderBottom(1).BorderColor(Colors.Grey.Lighten1)
                         .DefaultTextStyle(x => x.SemiBold().FontSize(10));

                    static IContainer CellBody(IContainer c) =>
                        c.PaddingVertical(6).PaddingHorizontal(5)
                         .BorderBottom(1).BorderColor(Colors.Grey.Lighten3);
                });

                // Totals
                col.Item().PaddingTop(15).AlignRight().Width(260).Column(t =>
                {
                    t.Item().Row(r => { r.RelativeItem().Text("Subtotal").SemiBold(); r.ConstantItem(120).AlignRight().Text($"{i.Subtotal:0.00} ден"); });
                    if (i.Discount != 0)
                        t.Item().Row(r => { r.RelativeItem().Text("Discount").SemiBold(); r.ConstantItem(120).AlignRight().Text($"- {i.Discount:0.00} ден"); });
                    if (i.Tax != 0)
                        t.Item().Row(r => { r.RelativeItem().Text("Tax").SemiBold(); r.ConstantItem(120).AlignRight().Text($"{i.Tax:0.00} ден"); });

                    t.Item().PaddingTop(6).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                    t.Item().Row(r =>
                    {
                        r.RelativeItem().Text("TOTAL").FontSize(12).SemiBold();
                        r.ConstantItem(120).AlignRight().Text($"{i.Total:0.00} ден").FontSize(12).SemiBold();
                    });
                });
            });
        }
    }
}
